### ISSUE TITLE
MySQL DECIMAL type issue

### ISSUE THREAD

**Issue by aglover** [readysettech/readyset#143]
See @cameronbraid's [project](https://github.com/cameronbraid/readyset_seaorm_issues) -- I was able to reproduce the issue following the provided directions. I updated the compose file to point to later versions of RS & MySQL and verified same behavior.  

Error message:

```
2023-08-05T23:28:45.912380Z DEBUG sqlx::query: summary="SELECT `has_decimal`.`id`, `has_decimal`.`price` FROM …" db.statement="\n\nSELECT\n  `has_decimal`.`id`,\n  `has_decimal`.`price`\nFROM\n  `has_decimal`\nWHERE\n  `has_decimal`.`id` = ?\nLIMIT\n  ?\n" rows_affected=0 rows_returned=1 elapsed=190.57175ms
Error: Query Error: error occurred while decoding column "price": mismatched types; Rust type `core::option::Option<rust_decimal::decimal::Decimal>` (as SQL type `DECIMAL`) is not compatible with SQL type `DECIMAL`

Caused by:
    error occurred while decoding column "price": mismatched types; Rust type `core::option::Option<rust_decimal::decimal::Decimal>` (as SQL type `DECIMAL`) is not compatible with SQL type `DECIMAL`

Location:
    app/src/bin/has_decimal.rs:26:17
```

**Comment by aglover** [comment]
@cameronbraid -- thank you for providing a way to reproduce the issue!

**Comment by lukoktonos** [comment]
Summary from discord conversation:

The issue here is that sqlx is not permissive enough to accept the rust_decimal value we are returning, despite the values used in the reproduction being well within the scale of 28 that rust_decimal supports. @cameronbraid has kindly made a [PR](https://github.com/launchbadge/sqlx/pull/2688) to sqlx that would unblock support there.

Closing this issue given that the change will need to be outside of the readyset codebase unless we fully rework our decimal/numeric to use a sqlx-supported type in this case, which we don't have immediate plans to do.
