### ISSUE TITLE
URL Parse error seen for certain MySQL connection strings

### ISSUE THREAD

**Issue by gvsg-rs** [readysettech/readyset#255]
### Summary

When connecting to certain MySQL URLs to connect to the upstream DB, ReadySet exits with a URL Parse error.

### Description

See Summary.

### Expected behavior

ReadySet should not fail for these URLs as they are valid DB URLs.

### Actual behavior

ReadySet fails to parse the URL with a port number error and exits.

### Steps to reproduce

Run a ReadySet docker container with the following sample docker config parameters. The user reported that a similar docker config with a shorter/simpler password worked. The password and IP in the example below are not real.

docker run -d
\--name=speeddb
\--publish=3307:3307
\--platform=linux/amd64
\--volume='readyset:/state'
\--pull=always
\-e DEPLOYMENT_ENV=quickstart_github
public.ecr.aws/readyset/readyset:beta-2023-04-19
\--standalone
\--deployment='github-mysql'
\--database-type=mysql
\--upstream-db-url=mysql://superadmin:'**SomelongPassswordasdf34#'**@'52.56.67.75':3306/'DEV_DB' \\
\--address=0.0.0.0:3307
\--username='tiger'
\--password='somepassword'
\--db-dir='/state'

### ReadySet version

This was tried with both readyset:beta-2023-04-19 and beta-2023-07-26 (commit: ba7370ee2195179faf33e98a303595e382a46498)

### Upstream DB type and version

MySQL (version not known. The error happens before connecting to the backendDB)

### Instance Details

N/A

### Deployment Details

```
Docker on Linux
```

### Logs

ERROR replicators: Error in replication, will retry after timeout error=The provided query is invalid: Invalid URL supplied to --upstream-db-url: URL parse error: invalid port number timeout_sec=30

**Comment by ethan-readyset** [comment]
This is an issue with URI character encoding. In a URL, the hash sign (`#`) starts the [URI fragment](https://en.wikipedia.org/wiki/URI_fragment), so it is not valid as an unescaped character in the password field. Unfortunately, the `mysql_async` and `tokio_postgres` libraries handle this differently. `mysql_async::Conn::from_url` fails with the same "invalid port" error seen above (I'm guessing it just uses `Url::parse` under the hood). `tokio_postgres::connect` does not blow up because it implements its own URL parser.

The good news is that both `mysql_async` and `tokio_postgres` both support already-percent-escaped URLs, so I believe the solution here is to percent-encode the URL string given to us by the user (encoding the same character set encoded by [this function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent), since `#` is part of the URL syntax). It may make sense to build our own abstraction around this to prevent future foot guns (e.g. calling `Url::password` on a `Url` that was created from a percent-encoded literal [will return the percent-encoded password](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=2e3283056b71d3df45cb8effa96e5865), which is probably not what we want).

**Comment by ethan-readyset** [comment]
Addendum: I don't think we should require that users escape the URLs themselves because I tested with `psql`, and it doesn't require escaping.

**Comment by lukoktonos** [comment]
It doesn't look like simply percent-encoding the connection strings before passing them to `mysql_async` will work here--doing so results in the library throwing a `RelativeUrlWithoutBase` error. It would probably work to only percent-encode the separate fields, but that would mean fully handling the parsing here. It's possible to do that but not worth the extra complexity IMO.

I think it's reasonable to document that users need to escape special characters in their connection strings. While `psql` does handle `#`, it doesn't handle other special characters that are valid to be included in passwords but part of the uri like `@` and `:`. So the postgres docs do say to use percent-encoding where necessary.

> Percent-encoding may be used to include symbols with special meaning in any of the URI parts, e.g., replace `=` with `%3D`.
>
> [https://www.postgresql.org/docs/11/libpq-connect.html#id-1.7.3.8.3.6](https://www.postgresql.org/docs/11/libpq-connect.html#id-1.7.3.8.3.6)

The `mysql` command-line tool itself does not accept connection strings in the same way, but looking at some other places that do support a mysql connection string like this, it seems like the norm is to provide documentation that users uri-encode things [\[1\]](https://www.prisma.io/docs/reference/database-reference/connection-urls#special-characters) [\[2\]](https://dev.mysql.com/doc/refman/8.0/en/connecting-using-uri-or-key-value-pairs.html#connecting-using-uri) 

So to fix this currently confusing user experience, we should instead:

1. Add documentation about needing to uri-encode
2. Make the error message something more reasonable than "invalid port"

**Comment by lukoktonos** [comment]
error message improvement: [https://gerrit.readyset.name/c/readyset/+/5837](https://gerrit.readyset.name/c/readyset/+/5837)

**Comment by lukoktonos** [comment]
docs update: [https://github.com/readysettech/docs/compare/upstream-db-url-docs?expand=1](https://github.com/readysettech/docs/compare/upstream-db-url-docs?expand=1)
