### ISSUE TITLE
Enable metrics in show proxied/caches command

### ISSUE THREAD

**Issue by aglover** [readysettech/readyset#394]
We can simplify the user experience by capturing what the python metrics script as part of the `show proxied/caches` commands. In addition to the query + status, let's add essentially what's listed w/count and P values. 

![Screenshot 2023-08-22 at 4.12.35 PM.png](https://uploads.linear.app/76d4be3b-10f5-452e-a0bd-5ce299bfcdf4/deecacd6-9eda-45d3-ac16-8ab1d0d17a3f/e7bb1042-b034-486a-9609-5f1831c7a0c0?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzc2ZDRiZTNiLTEwZjUtNDUyZS1hMGJkLTVjZTI5OWJmY2RmNC9kZWVjYWNkNi05ZWRhLTQ1ZDMtYWMxNi04YWIxZDBkMTdhM2YvZTdiYjEwNDItYjAzNC00ODZhLTk2MDktNWYxODMxYzdhMGMwIiwiaWF0IjoxNjkyNzQxNzUyLCJleHAiOjE2OTI4MjgxNTJ9.W9SdkK4bDJK8Q6ByR-VY76muHFjOO1ikVR_pCjF8Q9Q)

**Comment by aglover** [comment]
In completing this issue we also have an opportunity to remove Grafana dependency.

**Comment by dfwilbanks395** [comment]
Investigated how to support processing metrics in the adapter since the `PrometheusRecorder` since the only way to inspect metrics stored in the recorder is to render them all in the prometheus format. We have a few options

1. Fork `metrics-exporter-prometheus` to allow introspection of the `PrometheusRecorder`. We could also open an issue to see if the maintainers would be open to exposing more of the `PrometheusRecorder` internals.
2. Rely on the `PrometheusRecorder` to render the metrics and then introduce a new crate to parse the rendered metrics.
3. Use a separate metrics recorder (e.g., `NoriaMetricsRecorder`) for metrics we expose at the adapter. We'd probably want to disable this recorder in production to avoid the overhead of two recorders.
4. Maintain our own metrics recorder with support for rendering prometheus formatted metrics. I dove into this solution a bit, and rendering prometheus formatted metrics is pretty straightforward since `metrics-exporter-prometheus` exposes a formatting library. The crate also exposes the summary/histograms used which we could leverage to avoid implementing our own rolling summary. We don't use the scrape and push gateway support from that crate, but if we did want to rely on the push gateway in the future, we would have to figure out a solution for that.


Leaning towards option 4 (using our metrics recorder) since the risk of maintaining prometheus support doesn't seem too high.

**Comment by lukoktonos** [comment]
[https://gerrit.readyset.name/c/readyset/+/5979](https://gerrit.readyset.name/c/readyset/+/5979) adds the p50, p90, p99, but not count

[https://gerrit.readyset.name/c/readyset/+/6018](https://gerrit.readyset.name/c/readyset/+/6018) will add count as well

**Comment by aglover** [comment]
Something is flakey with our metrics and to ensure we don't overlook this I'm reopening this ticket.

**Comment by aglover** [comment]
Related: [REA-3540](https://linear.app/readyset/issue/REA-3540/show-caches-histograms-reset)
