### ISSUE TITLE
Silent data corruption with MySqlPosition::position been u32

### ISSUE THREAD

**Issue by altmannmarcelo** [readysettech/readyset#465]
**Describe the problem**
There is a possibility of `MySqlPosition::position` u32 overflow, which can cause readyset to skip replication events causing its internal state to be corrupted.

While investigating the issue, I can see that the physical information in the binlog overflows as well, this turned out to be a flaw in the MySQL binlog protocol design which Oracle has confirmed - https://bugs.mysql.com/bug.php?id=112189

The problem lies in the fact that MySQL does not spread a single transaction between multiple binary logs, and thus if the workload has a transaction that
exceeds `u32::MAX`, the `end_pos` field will overflow and start from 0. Making readyset think this is an event that has already been applied:

```
2023-08-27T16:39:42.311995Z WARN replicators::noria_adapter: Skipping table action for earlier entry table=test.big pos=binlog.000002:698 cur=binlog.000002:4294966874
2023-08-27T16:39:42.312016Z WARN replicators::noria_adapter: Skipping table action for earlier entry table=test.big pos=binlog.000002:1818 cur=binlog.000002:4294966874
2023-08-27T16:39:42.312024Z WARN replicators::noria_adapter: Skipping table action for earlier entry table=test.big pos=binlog.000002:2938 cur=binlog.000002:4294966874
2023-08-27T16:39:42.312031Z WARN replicators::noria_adapter: Skipping table action for earlier entry table=test.big pos=binlog.000002:4058 cur=binlog.000002:4294966874
```

The second problem with this is with regards to the `request_binlog` function which uses `mysql_common::packets::ComBinlogDump`. 
This API only accepts the start position as `u32` and in case of a disconnection from readyset to MySQL while we are processing a position above the `u32::MAX` range, the binlog API will not accept readyset's start position. There is a variant of this API, which is `mysql_common::packets::ComBinlogDumpGtid` but that will only work if the upstream server is configured with `gtid_mode=ON` which is not the default. Thus I think readyset should initiate a new snapshot in this case.

**To Reproduce**
I have a reproducible test case to explore this scenario at https://gist.github.com/altmannmarcelo/a71b672a4c1b6c9b30ed2ed66b19295b

Once readyset has finalized to apply the big transaction, its state of the data is corrupted and thus it reports a different resultset if compared with the upstream MySQL server:

```
# Upstream
mysql> SELECT COUNT(*) FROM user WHERE name = 'marce';
+----------+
| COUNT(*) |
+----------+
| 412 |
+----------+
1 row in set (0,00 sec)

# Readyset
readyset> SELECT COUNT(*) FROM user WHERE name = 'marce';
+----------+
| count(*) |
+----------+
| 377 |
+----------+
1 row in set (0,00 sec)
```

**Expected behavior**

**Additional data / screenshots**
N/A

**Environment**
 - ReadySet version - Latest from main
 - ReadySet deployment method - Manually Compiled
 - Upstream database and version - MySQL 8.0.34
 - Client app - MySQL

**Additional context**
The internal state of readyset gets corrupted.

I am currently testing a fix for this and planning to submit via PR

**Comment by glittershark** [comment]
> check how to trigger a new snapshot if we request a position beyond u32::MAX

Triggering resnapshots from the replicator is a little involved - lemme take a crack at an explanation for how this works today.

At a high level, any time we need to resnapshot we *drop* the table in RS, then *restart* the replicator thread (setting resnapshot to `true`). When the replicator starts up again, it notices that the dropped table is missing a replication offset, so it triggers a resnapshot of that table, then catches up every other table to the point at which that table was snapshotted before starting replication as usual again.

Probably the best example of this is what happens when we encounter an `ALTER TABLE` - we resnapshot on `ALTER TABLE` because we don't want to guarantee that we correctly handle everything an `ALTER TABLE` might do (eg it might change the type of a column using an expression, which we then have to evaluate 100% correctly). We return `ReadySetError::ResnapshotNeeded` [here](https://github.com/readysettech/readyset/blob/main/replicators/src/noria_adapter.rs#L730) (if the DDL change returns `true` from `requires_resnapshot`), then match on it [here](https://github.com/readysettech/readyset/blob/main/replicators/src/noria_adapter.rs#L243-L246) (where we just restart [this while loop](https://github.com/readysettech/readyset/blob/main/replicators/src/noria_adapter.rs#L184)). Then within the `mysql_connector` and `posgres_connector`, if `resnapshot` is `true`, we send `Change::CreateTable` for *all the tables* to ReadySet. Over on the ReadySet side, when we get that `Change::CreateTable`, we [check to see if the table's schema has changed and drop and recreate it if so](https://github.com/readysettech/readyset/blob/main/readyset-server/src/controller/sql/mod.rs#L251-L265). Then, when the replicator [loads replication offsets for all tables](https://github.com/readysettech/readyset/blob/main/replicators/src/mysql_connector/snapshot.rs#L521), it [skips over all tables that already have a replication offset](https://github.com/readysettech/readyset/blob/main/replicators/src/mysql_connector/snapshot.rs#L586-L590), resulting in us only resnapshotting the table that we dropped and recreated.


The change detection stuff probably isn't relevant in this case - for this, we can probably just drop and recreate the table (maybe via a new member of the `Change` enum?) and then restart the replicator by returning `Err(ReadySetError::ResnapshotNeeded)`.

Since this might get a little involved, it'd be awesome if you can break it up into a sequence of separate PRs so that we can review+merge bit by bit. Feel free to let me know if you have any questions / if there's anything in the above explanation I can clear up or go into more detail on.

**Comment by glittershark** [comment]
ah, yeah, that makes sense to me. Full resnapshot it is then!

Still interested in hearing from @ethan-readyset here - it's possible there's something in pg-land that might want a general ability to trigger a full resnapshot, which might help guide our approach here

**Comment by ethan-readyset** [comment]
@altmannmarcelo The changes I've been making have been pretty specific to the Postgres code paths, so your changes here shouldn't conflict -- thanks for finding and reporting this! I agree that a full resnapshot sounds like the right approach here. I also don't think anything in the Postgres code path currently requires the ability to trigger a full resnapshot, so no need to worry about factoring that into your approach 😄

**Comment by ethan-readyset** [comment]
@altmannmarcelo Looking more closely at #239, I do think we'll need to trigger a full resnapshot in the Postgres code when our replication slot becomes invalidated, but it looks like the Postgres connector [already drops any existing tables prior to doing a snapshot if the `full_snapshot` parameter is passed](https://github.com/readysettech/readyset/blob/fb3251bb8c1e18cc004615a614edb284a443d73c/replicators/src/postgres_connector/snapshot.rs#L790), so I will probably make use of that by adding a `ReadySetError::FullResnapshotNeeded` error variant that will prompt a full resnapshot after our replicator restarts upon receiving an error that requires a full resnapshot.

It might make sense to take a similar approach in the MySQL code path by adding a `full_snapshot` parameter to the `MySqlReplicator::snapshot_to_noria()` method. Let me know if that makes sense!

**Comment by glittershark** [comment]
@altmannmarcelo was #530 the last thing required to fix this?

**Comment by altmannmarcelo** [comment]
@glittershark Yes, both PRs related to this issue are merged 🎉 .
